// +build !ignore_autogenerated

/*
Copyright 2020 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package templatings

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Templatings) DeepCopyInto(out *Templatings) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(VariableInterval)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(VariableCustom)
		(*in).DeepCopyInto(*out)
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(VariableQuery)
		**out = **in
	}
	if in.Const != nil {
		in, out := &in.Const, &out.Const
		*out = new(VariableConst)
		(*in).DeepCopyInto(*out)
	}
	if in.Datasource != nil {
		in, out := &in.Datasource, &out.Datasource
		*out = new(VariableDatasource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Templatings.
func (in *Templatings) DeepCopy() *Templatings {
	if in == nil {
		return nil
	}
	out := new(Templatings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableConst) DeepCopyInto(out *VariableConst) {
	*out = *in
	if in.ValuesMap != nil {
		in, out := &in.ValuesMap, &out.ValuesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableConst.
func (in *VariableConst) DeepCopy() *VariableConst {
	if in == nil {
		return nil
	}
	out := new(VariableConst)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableCustom) DeepCopyInto(out *VariableCustom) {
	*out = *in
	if in.ValuesMap != nil {
		in, out := &in.ValuesMap, &out.ValuesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableCustom.
func (in *VariableCustom) DeepCopy() *VariableCustom {
	if in == nil {
		return nil
	}
	out := new(VariableCustom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableDatasource) DeepCopyInto(out *VariableDatasource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableDatasource.
func (in *VariableDatasource) DeepCopy() *VariableDatasource {
	if in == nil {
		return nil
	}
	out := new(VariableDatasource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableInterval) DeepCopyInto(out *VariableInterval) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableInterval.
func (in *VariableInterval) DeepCopy() *VariableInterval {
	if in == nil {
		return nil
	}
	out := new(VariableInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableQuery) DeepCopyInto(out *VariableQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableQuery.
func (in *VariableQuery) DeepCopy() *VariableQuery {
	if in == nil {
		return nil
	}
	out := new(VariableQuery)
	in.DeepCopyInto(out)
	return out
}
